// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-direct:default`.
const COMMANDS: &[&str] = &[
    "direct_start_room",
    "direct_stop_room",
    "direct_room_status",
    "direct_answer_join",
    "direct_lan_rooms",
    "direct_stop_discovery",
    "direct_open_ports",
    "direct_close_ports",
    "direct_port_status",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
