// Commands exposed by this plugin. The tauri-plugin build helper turns each
// into autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-uberstress:default`.
const COMMANDS: &[&str] = &[
    "us_scenarios",
    "us_run",
    "us_cancel",
    "us_history",
    "us_report",
    "us_config_get",
    "us_config_set",
    "us_seed_sql",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
