// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-scenario:default`.
const COMMANDS: &[&str] = &[
    "scenario_list",
    "scenario_save",
    "scenario_delete",
    "scenario_media_import",
    "scenario_media_delete",
    "scenario_media_read",
    "scenario_media_write",
    "scenario_read_mission",
    "scenario_runtime_install",
    "scenario_runtime_status",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
