// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-hub:default`.
const COMMANDS: &[&str] = &["hub_sign_in", "hub_sign_out", "hub_account"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
