// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-play:default`.
const COMMANDS: &[&str] = &["play_generate_script", "play_launch", "play_cancel"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
