// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-play:default`.
const COMMANDS: &[&str] = &[
    "play_generate_script",
    "play_export_script",
    "play_export_preset",
    "play_import_preset",
    "play_launch",
    "play_launch_replay",
    "play_launch_save",
    "play_cancel",
    "play_focus",
    "play_infolog",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
