// Commands exposed by this plugin. The tauri-plugin build helper turns each
// into autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-workshop:default`.
const COMMANDS: &[&str] = &[
    "workshop_compile",
    "workshop_preflight",
    "workshop_test_mutator",
    "workshop_package_mutator",
    "workshop_pack_bar_slots",
    "workshop_decode_tweak_set",
    "workshop_change_ledger",
    "workshop_write_in_place",
    "workshop_in_place_status",
    "workshop_undo_in_place",
    "workshop_accept_in_place",
    "workshop_check_in_place",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
