// Commands exposed by this plugin. The tauri-plugin build helper turns each
// into autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-workshop:default`.
const COMMANDS: &[&str] = &[
    "workshop_compile",
    "workshop_preflight",
    "workshop_test_mutator",
    "workshop_package_mutator",
    "workshop_pack_bar_slots",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
