// Commands exposed by this plugin. The tauri-plugin build helper turns each
// into autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-content:default`.
const COMMANDS: &[&str] = &[
    "content_candidates",
    "content_state_load",
    "content_rescan",
    "content_scan_root",
    "content_add_root",
    "content_remove_root",
    "content_list_engines",
    "content_verify_engine",
    "content_open_path",
    "content_list_replays",
    "content_demo_info",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
