// Commands exposed by this plugin. The tauri-plugin build helper turns each
// into autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-content:default`.
const COMMANDS: &[&str] = &[
    "content_candidates",
    "content_state_load",
    "content_rescan",
    "content_scan_root",
    "content_add_root",
    "content_create_standard_root",
    "content_recreate_root",
    "content_remove_root",
    "content_list_engines",
    "content_verify_engine",
    "content_open_path",
    "content_list_replays",
    "content_demo_info",
    "content_demo_chat",
    "content_rewrite_demo",
    "content_delete_replay",
    "content_list_saves",
    "content_delete_save",
    "content_config_profiles",
    "content_config_backup",
    "content_config_restore",
    "content_config_delete_profile",
    "content_warm_rapid_pool",
    "content_prune_rapid_pool",
    "content_reclaim_caches",
    "branding_catalog",
    "branding_image",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
