// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-campaign:default`.
const COMMANDS: &[&str] = &[
    "campaign_list",
    "campaign_save",
    "campaign_delete",
    "campaign_image_import",
    "campaign_image_import_data",
    "campaign_image_read",
    "campaign_media_delete",
    "campaign_media_import",
    "campaign_media_import_data",
    "campaign_export",
    "campaign_import",
    "campaign_progress_load",
    "campaign_progress_save",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
