// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-unitsync:default`.
const COMMANDS: &[&str] = &[
    "unitsync_scan",
    "unitsync_minimap",
    "unitsync_heightmap",
    "unitsync_thumbnails",
    "unitsync_game_info",
    "unitsync_map_info",
    "unitsync_skirmish_ais",
    "unitsync_engine_config",
    "unitsync_archive_tree",
    "unitsync_archive_file",
    "unitsync_lua_exec",
    "unitsync_archive_extract",
    "unitsync_cancel",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
