// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-unitsync:default`.
const COMMANDS: &[&str] = &[
    "unitsync_scan",
    "unitsync_minimap",
    "unitsync_heightmap",
    "unitsync_height_field",
    "unitsync_metalmap",
    "unitsync_thumbnails",
    "unitsync_map_meta",
    "unitsync_game_info",
    "unitsync_unit_buildpics",
    "unitsync_faction_logos",
    "unitsync_unit_dataset",
    "unitsync_unit_model",
    "unitsync_unit_models",
    "unitsync_unit_render",
    "unitsync_unit_render_keys",
    "unitsync_remember_render",
    "unitsync_local_renders",
    "unitsync_map_catalog",
    "unitsync_map_info",
    "unitsync_map_skybox",
    "unitsync_skirmish_ais",
    "unitsync_engine_config",
    "unitsync_engine_config_set",
    "unitsync_archive_tree",
    "unitsync_archive_file",
    "unitsync_game_headers",
    "unitsync_lua_exec",
    "unitsync_lua_repl_exec",
    "unitsync_archive_extract",
    "unitsync_cancel",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
