// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-lego:default`.
const COMMANDS: &[&str] = &[
    "lego_list",
    "lego_save",
    "lego_delete",
    "lego_thumb_save",
    "lego_open_path",
    "lego_packs",
    "lego_read_s3o",
    "lego_export",
    "lego_export_glb",
    "lego_export_obj",
    "lego_scratch_game",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
