// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-profile:default`.
const COMMANDS: &[&str] = &[
    "profile_load",
    "profile_asset",
    "profile_file",
    "profile_pages",
    "profile_scaffold",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
