// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-conquest:default`.
const COMMANDS: &[&str] = &[
    "conquest_list",
    "conquest_save",
    "conquest_delete",
    "conquest_state_load",
    "conquest_state_save",
    "conquest_map_list",
    "conquest_map_stage",
    "conquest_map_commit",
    "conquest_map_discard",
    "conquest_map_remove",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
