/**
 * Generate a Recoil unit script for a built unit.
 *
 * Lua, not BOS. The full set of callins is always written, even with no
 * animation applied, so an early export already loads and runs rather than
 * erroring on a missing hook.
 *
 * Only pieces the script actually references get a local, so a sixty piece
 * unit does not open with sixty declarations. Piece names come from the
 * document, where they are already lower case and identifier-safe.
 */

import {
  type AnimPreset,
  type EmitResult,
  type LuaHook,
  presetById,
} from "./animPresets";
import type { LegoProject } from "./model";

/**
 * Lua's reserved words. A piece called `end` is a legal piece name and an
 * illegal local, so those get a prefix while the piece keeps its real name.
 */
const RESERVED = new Set([
  "and",
  "break",
  "do",
  "else",
  "elseif",
  "end",
  "false",
  "for",
  "function",
  "goto",
  "if",
  "in",
  "local",
  "nil",
  "not",
  "or",
  "repeat",
  "return",
  "then",
  "true",
  "until",
  "while",
]);

function localName(piece: string): string {
  return RESERVED.has(piece) ? `p_${piece}` : piece;
}

/**
 * The callins, in the order they are written.
 *
 * `Killed` is deliberately not here: it always explodes the root piece and
 * returns 1 regardless of what is applied, so it keeps its own hardcoded
 * block below. A preset can still contribute to it through `hooks`, same as
 * any other callin, that block just reads the map directly instead of going
 * through this list.
 */
const HOOKS: { hook: LuaHook; signature: string }[] = [
  { hook: "Create", signature: "script.Create()" },
  { hook: "StartMoving", signature: "script.StartMoving()" },
  { hook: "StopMoving", signature: "script.StopMoving()" },
  { hook: "Activate", signature: "script.Activate()" },
  { hook: "Deactivate", signature: "script.Deactivate()" },
  { hook: "AimWeapon1", signature: "script.AimWeapon1(heading, pitch)" },
  { hook: "AimFromWeapon1", signature: "script.AimFromWeapon1()" },
  { hook: "QueryWeapon1", signature: "script.QueryWeapon1()" },
  { hook: "Shot1", signature: "script.Shot1()" },
];

/** What a callin returns when no preset has anything to say. */
const HOOK_FALLBACK: Partial<Record<LuaHook, string[]>> = {
  AimWeapon1: ["  return true"],
};

export function buildLuaScript(project: LegoProject): string {
  const used = new Set<string>();
  const byRole = new Map<string, string[]>();
  for (const piece of project.pieces) {
    if (!piece.role) continue;
    byRole.set(piece.role, [...(byRole.get(piece.role) ?? []), piece.name]);
  }

  const functions: string[] = [];
  const hooks = new Map<LuaHook, string[]>();
  const signals: string[] = [];

  const applied = (project.animations ?? [])
    .map((entry) => ({
      preset: presetById(entry.presetId),
      params: entry.params,
    }))
    .filter(
      (
        entry,
      ): entry is { preset: AnimPreset; params: Record<string, number> } =>
        entry.preset !== undefined,
    );

  applied.forEach(({ preset, params }, index) => {
    const signal = `SIG_${preset.id.replace(/[^a-z0-9]+/gi, "_").toUpperCase()}`;
    const result: EmitResult | null = preset.emit({
      params,
      signal,
      pieces(role) {
        const names = byRole.get(role) ?? [];
        for (const name of names) used.add(name);
        return names.map(localName);
      },
    });
    if (!result) return;

    signals.push(`local ${signal} = ${1 << index}`);
    if (result.functions.length > 0) {
      functions.push(`-- ${preset.label}`, ...result.functions, "");
    }
    for (const [hook, lines] of Object.entries(result.hooks)) {
      hooks.set(hook as LuaHook, [
        ...(hooks.get(hook as LuaHook) ?? []),
        ...lines,
      ]);
    }
  });

  const root = project.pieces.find(
    (piece) => piece.id === project.rootPieceId,
  )?.name;
  if (root) used.add(root);

  const declared = project.pieces
    .filter((piece) => used.has(piece.name))
    .map((piece) => piece.name);

  const out: string[] = [
    `-- ${project.unitName}, generated by coilbox's unit builder.`,
    "-- Safe to edit: nothing regenerates this file unless you export again.",
    "",
    ...declared.map((piece) => `local ${localName(piece)} = piece("${piece}")`),
    ...(declared.length > 0 ? [""] : []),
    ...signals,
    ...(signals.length > 0 ? [""] : []),
    ...functions,
  ];

  for (const { hook, signature } of HOOKS) {
    const lines = hooks.get(hook) ?? HOOK_FALLBACK[hook] ?? [];
    out.push(`function ${signature}`, ...lines, "end", "");
  }

  out.push(
    "function script.Killed(recentDamage, maxHealth)",
    ...(hooks.get("Killed") ?? []),
    ...(root ? [`  Explode(${localName(root)}, SFX.SHATTER)`] : []),
    "  return 1",
    "end",
    "",
  );

  // One trailing newline, and no runs of blank lines from empty sections.
  return `${out
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}
