/**
 * Generate a Recoil/Spring unit definition for a built unit.
 *
 * Small on purpose: the fields the engine needs to accept the unit and put it
 * on the map, not a full customisation surface. Its job is to unblock the
 * engine load test, not to replace hand-tuning a unit afterwards.
 *
 * Written as a static structure. The builder has no notion of movement
 * classes yet, and a unit with `canMove` set but no matching `movementClass`
 * is rejected outright at load: UnitDefHandler logs an error and drops it, so
 * the whole point of this file (something to spawn) is lost. Leaving
 * movement off is what keeps every export loadable. Nothing has to build the
 * unit either, because the scratch game makes it the side's start unit, so a
 * static unit is still one you meet in a match.
 *
 * `objectname` has to resolve. The engine's own `gamedata/unitdefs.lua` drops
 * any definition whose model is missing, before the unit ever reaches the
 * game, so an export that writes a definition without its `.s3o` produces a
 * unit that silently does not exist.
 */

import type { LegoProject } from "./model";

/**
 * World units (elmos) per footprint step. The blocking map's square is two of
 * the engine's SQUARE_SIZE (8 elmos), so a footprint of 1 covers 16 elmos.
 * See UnitDef.cpp (`xsize = footprintX * SPRING_FOOTPRINT_SCALE`) and
 * GlobalConstants.h (`SPRING_FOOTPRINT_SCALE = 2`, `SQUARE_SIZE = 8`).
 */
export const ELMOS_PER_FOOTPRINT = 16;

/** A conservative stand-in health value, easy to find and retune by hand. */
const DEFAULT_MAX_DAMAGE = 1000;

/** Quote a value as a Lua string literal. Shared with the scratch game's modinfo. */
export function luaString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/**
 * `sizeX` and `sizeZ` are the model's world-space bounding-box extent along
 * each ground axis, in elmos, as `buildS3o`'s header measures them. Each axis
 * gets its own footprint step rather than one step shared from a collision
 * radius, so a unit longer than it is wide claims a rectangle of ground
 * rather than the square that would fit its longest axis.
 *
 * This measures the whole bounding box, including anything that sticks out
 * such as a gun barrel or an aerial. A real game would usually trim those
 * from a building's footprint, but the builder has no notion yet of which
 * pieces are structural rather than attached, so there is nothing narrower to
 * measure from.
 *
 * Each axis rounds up to the next whole step rather than to the nearest one.
 * A footprint is the ground the engine uses for placement and pathing, and
 * rounding to nearest can round down, which would leave a unit's own
 * footprint too small to contain it. Rounding up always wastes a little
 * space instead, which is the safer failure. A unit smaller than one step
 * still gets at least 1, matching the engine's own minimum.
 */
export function buildUnitDef(
  project: LegoProject,
  size: { x: number; z: number },
): string {
  const footprintx = footprintSteps(size.x);
  const footprintz = footprintSteps(size.z);

  const fields: [string, string][] = [
    ["name", luaString(project.name)],
    [
      "description",
      luaString(`${project.name}, built with coilbox's unit builder.`),
    ],
    ["objectname", luaString(project.unitName)],
    ["script", luaString(`${project.unitName}.lua`)],
    ["footprintx", String(footprintx)],
    ["footprintz", String(footprintz)],
    ["maxdamage", String(DEFAULT_MAX_DAMAGE)],
    ["canmove", "false"],
  ];

  const lines = [
    `-- ${project.unitName}, generated by coilbox's unit builder.`,
    "-- Safe to edit: nothing regenerates this file unless you export again.",
    "",
    "return {",
    `  ["${project.unitName}"] = {`,
    ...fields.map(([key, value]) => `    ${key} = ${value},`),
    "  },",
    "}",
  ];

  return `${lines.join("\n")}\n`;
}

/**
 * One axis's extent, in elmos, to a whole number of footprint steps. Rounds
 * up so the step always contains the axis it was measured from. A tiny or
 * empty extent still steps up to 1, the engine's own minimum footprint.
 * The `1e-9` slack absorbs float error from the box measurement so a size
 * that lands exactly on a step boundary is not pushed into the next one.
 */
function footprintSteps(size: number): number {
  return Math.max(1, Math.ceil(size / ELMOS_PER_FOOTPRINT - 1e-9));
}
