/**
 * Generate a Recoil/Spring unit definition for a built unit.
 *
 * Small on purpose: the fields the engine needs to accept the unit and put it
 * on the map, not a full customisation surface. Its job is to unblock the
 * engine load test, not to replace hand-tuning a unit afterwards.
 *
 * Written as a static structure. The builder has no notion of movement
 * classes yet, and a unit with `canMove` set but no matching `movementClass`
 * is rejected outright at load: UnitDefHandler logs an error and drops it, so
 * the whole point of this file (something to spawn) is lost. Leaving
 * movement off is what keeps every export loadable.
 */

import type { LegoProject } from "./model";

/**
 * World units (elmos) per footprint step. The blocking map's square is two of
 * the engine's SQUARE_SIZE (8 elmos), so a footprint of 1 covers 16 elmos.
 * See UnitDef.cpp (`xsize = footprintX * SPRING_FOOTPRINT_SCALE`) and
 * GlobalConstants.h (`SPRING_FOOTPRINT_SCALE = 2`, `SQUARE_SIZE = 8`).
 */
export const ELMOS_PER_FOOTPRINT = 16;

/** A conservative stand-in health value, easy to find and retune by hand. */
const DEFAULT_MAX_DAMAGE = 1000;

/** Quote a value as a Lua string literal. Shared with the scratch game's modinfo. */
export function luaString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

/**
 * `radius` is the model's collision-sphere radius, in elmos, as `buildS3o`
 * computes it. The footprint is derived from it rather than left at the
 * engine's 1x1 default, so units built from bigger or smaller assemblies do
 * not all claim the same ground space.
 */
export function buildUnitDef(project: LegoProject, radius: number): string {
  const footprint = Math.max(1, Math.round((radius * 2) / ELMOS_PER_FOOTPRINT));

  const fields: [string, string][] = [
    ["name", luaString(project.name)],
    [
      "description",
      luaString(`${project.name}, built with coilbox's unit builder.`),
    ],
    ["objectname", luaString(project.unitName)],
    ["script", luaString(`${project.unitName}.lua`)],
    ["footprintx", String(footprint)],
    ["footprintz", String(footprint)],
    ["maxdamage", String(DEFAULT_MAX_DAMAGE)],
    ["canmove", "false"],
  ];

  const lines = [
    `-- ${project.unitName}, generated by coilbox's unit builder.`,
    "-- Safe to edit: nothing regenerates this file unless you export again.",
    "",
    "return {",
    `  ["${project.unitName}"] = {`,
    ...fields.map(([key, value]) => `    ${key} = ${value},`),
    "  },",
    "}",
  ];

  return `${lines.join("\n")}\n`;
}
