"$schema" = "schemas/schema.json"

[default]
description = "Allows the multiplayer lobby client's connection, state, chat, battle and hosting commands."
permissions = [
  "allow-mp-connect",
  "allow-mp-connect-tachyon",
  "allow-mp-register",
  "allow-mp-confirm-agreement",
  "allow-mp-disconnect",
  "allow-mp-cancel-connect",
  "allow-mp-reattach",
  "allow-mp-active-keys",
  "allow-mp-snapshot",
  "allow-mp-send",
  "allow-mp-say",
  "allow-mp-say-private",
  "allow-mp-say-battle",
  "allow-mp-say-ex",
  "allow-mp-say-battle-ex",
  "allow-mp-say-private-ex",
  "allow-mp-join-channel",
  "allow-mp-leave-channel",
  "allow-mp-list-channels",
  "allow-mp-ignore",
  "allow-mp-unignore",
  "allow-mp-ignore-list",
  "allow-mp-friend-request",
  "allow-mp-accept-friend-request",
  "allow-mp-decline-friend-request",
  "allow-mp-unfriend",
  "allow-mp-friend-list",
  "allow-mp-friend-request-list",
  "allow-mp-join-battle",
  "allow-mp-join-battle-deny",
  "allow-mp-leave-battle",
  "allow-mp-set-status",
  "allow-mp-set-battle-status",
  "allow-mp-open-battle",
  "allow-mp-update-battle-info",
  "allow-mp-add-bot",
  "allow-mp-remove-bot",
  "allow-mp-update-bot",
  "allow-mp-force-team",
  "allow-mp-force-ally",
  "allow-mp-force-color",
  "allow-mp-force-spectator",
  "allow-mp-kick",
  "allow-mp-appoint-boss",
  "allow-mp-unboss",
  "allow-mp-set-start-rect",
  "allow-mp-remove-start-rect",
  "allow-mp-set-script-tags",
  "allow-mp-remove-script-tags",
  "allow-mp-build-battle-config",
  "allow-mp-build-host-config",
  "allow-mp-probe-host",
  "allow-mp-chat-logs",
  "allow-mp-chat-log-open",
  "allow-mp-tachyon-sign-in",
  "allow-mp-tachyon-sign-out",
  "allow-mp-tachyon-request",
]
