"$schema" = "schemas/schema.json"

[default]
description = "Allows the multiplayer lobby client's connection, state, chat, battle and hosting commands."
permissions = [
  "allow-mp-connect",
  "allow-mp-register",
  "allow-mp-confirm-agreement",
  "allow-mp-disconnect",
  "allow-mp-reattach",
  "allow-mp-active-keys",
  "allow-mp-snapshot",
  "allow-mp-send",
  "allow-mp-say",
  "allow-mp-say-private",
  "allow-mp-say-battle",
  "allow-mp-say-ex",
  "allow-mp-say-battle-ex",
  "allow-mp-say-private-ex",
  "allow-mp-join-channel",
  "allow-mp-leave-channel",
  "allow-mp-list-channels",
  "allow-mp-join-battle",
  "allow-mp-join-battle-deny",
  "allow-mp-leave-battle",
  "allow-mp-set-status",
  "allow-mp-set-battle-status",
  "allow-mp-open-battle",
  "allow-mp-update-battle-info",
  "allow-mp-add-bot",
  "allow-mp-remove-bot",
  "allow-mp-update-bot",
  "allow-mp-force-team",
  "allow-mp-force-ally",
  "allow-mp-force-color",
  "allow-mp-force-spectator",
  "allow-mp-kick",
  "allow-mp-set-start-rect",
  "allow-mp-remove-start-rect",
  "allow-mp-set-script-tags",
  "allow-mp-remove-script-tags",
  "allow-mp-build-battle-config",
  "allow-mp-build-host-config",
]
