/**
 * Which of the two delivery routes a game actually supports (issue #1268).
 *
 * A change lands in a game one of two ways, and they are not equivalent. The
 * engine's own route is a mutator archive: a `.sdd`/`.sdz` whose `modinfo.lua`
 * depends on the base game and supplies only what changed. It needs no
 * cooperation from the base game and works for every Spring and Recoil game
 * there is, which is why `crates/tauri-plugin-coilbox-scenario/src/mutator.rs`
 * already writes one and why the compiler in #1275 targets it first.
 *
 * Beyond All Reason's route is different. A `tweakdefs`/`tweakunits` mod
 * option carries base64 Lua, which BAR's own code decodes and applies. That
 * is a policy choice specific to that game, not a general mechanism, so it is
 * only on offer when the game actually declares the slots. unitsync already
 * reads every mod option a game's `modoptions.lua` declares
 * (`GameInfoResult.options`, via `unitsync_game_info`), and BAR's own numbered
 * slots (`beyond-all-reason/Beyond-All-Reason`'s `modoptions.lua`) are keys of
 * the exact shape this module looks for: a bare `tweakdefs`/`tweakunits` plus
 * `tweakdefs1..29`/`tweakunits1..29`, generated by a loop over `options[]`.
 * `tweakdefs` carries executable Lua wrapped in `do ... end`, `tweakunits`
 * carries a plain table, and the compiler in #1275 already produces both
 * forms for that reason.
 *
 * The mutator route is the default that always works. The tweak-slot route is
 * additional, and only when the game says so.
 */
import type { ConfigOption } from "@/content/bindings";

/** One of the two ways a project's edits can reach a running game. */
export type DeliveryRoute = "mutator" | "tweak-slots";

/** How many BAR-style tweak slots a game's mod options declare, by kind. */
export interface TweakSlotCounts {
  defs: number;
  units: number;
}

/**
 * `tweakdefs`, `tweakunits`, or either with a number after it, the exact
 * shape BAR's `modoptions.lua` declares: bare for the one slot in the main
 * options list, and `1` through `29` for the hidden ones a loop adds under
 * `options_extra`. A game that copies the convention for its own slots reads
 * the same way. Nothing here is BAR-specific beyond the key shape BAR itself
 * defined.
 */
const TWEAK_KEY = /^tweak(defs|units)(\d+)?$/;

/** Count a game's declared tweak slots, split by which kind of Lua they carry. */
export function tweakSlotCounts(options: ConfigOption[]): TweakSlotCounts {
  let defs = 0;
  let units = 0;
  for (const o of options) {
    const m = TWEAK_KEY.exec(o.key);
    if (!m) continue;
    if (m[1] === "defs") defs += 1;
    else units += 1;
  }
  return { defs, units };
}

/** One route, whether the selected game supports it, and why when it does not. */
export interface RouteAvailability {
  route: DeliveryRoute;
  label: string;
  available: boolean;
  /** A line of detail worth showing either way: capacity when available,
   *  cause when it is not. */
  detail: string;
}

/**
 * The two routes for one game, in the order they are offered. The mutator is
 * always available. It is the one every game supports, and the one nothing
 * here needs to check. The tweak-slot route is available only when the game's
 * own mod options declare at least one `tweakdefs`/`tweakunits` slot, since a
 * project that only needs a plain table still needs somewhere to put it, so
 * either kind on its own counts.
 */
export function deliveryRoutes(
  options: ConfigOption[],
  gameName: string,
): RouteAvailability[] {
  const { defs, units } = tweakSlotCounts(options);
  const available = defs > 0 || units > 0;
  return [
    {
      route: "mutator",
      label: "Mutator archive",
      available: true,
      detail:
        "Works for every game: a generated game that depends on this one and supplies only what the project changes.",
    },
    {
      route: "tweak-slots",
      label: "BAR tweak slots",
      available,
      detail: available
        ? `${gameName} declares ${defs} tweakdefs slot${defs === 1 ? "" : "s"} and ${units} tweakunits slot${units === 1 ? "" : "s"} for base64 Lua.`
        : `${gameName} does not declare any tweakdefs or tweakunits mod options, so there is no slot to carry base64 Lua. The mutator route above still works.`,
    },
  ];
}
