// Generated by scripts/build-engine-keybinds.mjs. Do not edit.
// Source: RecoilEngine 2026.07.04, rts/Game/UI/KeyBindings.cpp and KeyCodes.cpp.
// Regenerate with: bun run keybinds:defaults

import type { Binding } from "./uikeys";

/** The RecoilEngine tag these tables were read from. */
export const ENGINE_KEYBIND_REF = "2026.07.04";

/** What the engine binds before it opens uikeys.txt, in its own order. */
export const ENGINE_DEFAULT_BINDINGS: Binding[] = [
  {
    keys: "esc",
    action: "quitmessage",
  },
  {
    keys: "Shift+esc",
    action: "quitmenu",
  },
  {
    keys: "Ctrl+Shift+esc",
    action: "quitforce",
  },
  {
    keys: "Alt+Shift+esc",
    action: "reloadforce",
  },
  {
    keys: "Any+pause",
    action: "pause",
  },
  {
    keys: "c",
    action: "controlunit",
  },
  {
    keys: "Any+h",
    action: "sharedialog",
  },
  {
    keys: "Any+i",
    action: "gameinfo",
  },
  {
    keys: "Any+j",
    action: "mouse2",
  },
  {
    keys: "backspace",
    action: "mousestate",
  },
  {
    keys: "Shift+backspace",
    action: "togglecammode",
  },
  {
    keys: "Ctrl+backspace",
    action: "togglecammode",
  },
  {
    keys: "Any+tab",
    action: "toggleoverview",
  },
  {
    keys: "Any+enter",
    action: "chat",
  },
  {
    keys: "Alt+ctrl+a,Alt+ctrl+a",
    action: "chatswitchally",
  },
  {
    keys: "Alt+ctrl+s,Alt+ctrl+s",
    action: "chatswitchspec",
  },
  {
    keys: "Any+tab",
    action: "edit_complete",
  },
  {
    keys: "Any+backspace",
    action: "edit_backspace",
  },
  {
    keys: "Any+delete",
    action: "edit_delete",
  },
  {
    keys: "Any+home",
    action: "edit_home",
  },
  {
    keys: "Alt+left",
    action: "edit_home",
  },
  {
    keys: "Any+end",
    action: "edit_end",
  },
  {
    keys: "Alt+right",
    action: "edit_end",
  },
  {
    keys: "Any+up",
    action: "edit_prev_line",
  },
  {
    keys: "Any+down",
    action: "edit_next_line",
  },
  {
    keys: "Any+left",
    action: "edit_prev_char",
  },
  {
    keys: "Any+right",
    action: "edit_next_char",
  },
  {
    keys: "Ctrl+left",
    action: "edit_prev_word",
  },
  {
    keys: "Ctrl+right",
    action: "edit_next_word",
  },
  {
    keys: "Any+enter",
    action: "edit_return",
  },
  {
    keys: "Any+escape",
    action: "edit_escape",
  },
  {
    keys: "Ctrl+v",
    action: "pastetext",
  },
  {
    keys: "Any+home",
    action: "increaseViewRadius",
  },
  {
    keys: "Any+end",
    action: "decreaseViewRadius",
  },
  {
    keys: "Alt+insert",
    action: "speedup",
  },
  {
    keys: "Alt+delete",
    action: "slowdown",
  },
  {
    keys: "Alt+=",
    action: "speedup",
  },
  {
    keys: "Alt++",
    action: "speedup",
  },
  {
    keys: "Alt+-",
    action: "slowdown",
  },
  {
    keys: "Alt+numpad+",
    action: "speedup",
  },
  {
    keys: "Alt+numpad-",
    action: "slowdown",
  },
  {
    keys: ",",
    action: "prevmenu",
  },
  {
    keys: ".",
    action: "nextmenu",
  },
  {
    keys: "Shift+,",
    action: "decguiopacity",
  },
  {
    keys: "Shift+.",
    action: "incguiopacity",
  },
  {
    keys: "1",
    action: "specteam 0",
  },
  {
    keys: "2",
    action: "specteam 1",
  },
  {
    keys: "3",
    action: "specteam 2",
  },
  {
    keys: "4",
    action: "specteam 3",
  },
  {
    keys: "5",
    action: "specteam 4",
  },
  {
    keys: "6",
    action: "specteam 5",
  },
  {
    keys: "7",
    action: "specteam 6",
  },
  {
    keys: "8",
    action: "specteam 7",
  },
  {
    keys: "9",
    action: "specteam 8",
  },
  {
    keys: "0",
    action: "specteam 9",
  },
  {
    keys: "Ctrl+1",
    action: "specteam 10",
  },
  {
    keys: "Ctrl+2",
    action: "specteam 11",
  },
  {
    keys: "Ctrl+3",
    action: "specteam 12",
  },
  {
    keys: "Ctrl+4",
    action: "specteam 13",
  },
  {
    keys: "Ctrl+5",
    action: "specteam 14",
  },
  {
    keys: "Ctrl+6",
    action: "specteam 15",
  },
  {
    keys: "Ctrl+7",
    action: "specteam 16",
  },
  {
    keys: "Ctrl+8",
    action: "specteam 17",
  },
  {
    keys: "Ctrl+9",
    action: "specteam 18",
  },
  {
    keys: "Ctrl+0",
    action: "specteam 19",
  },
  {
    keys: "Any+0",
    action: "group0",
  },
  {
    keys: "Any+1",
    action: "group1",
  },
  {
    keys: "Any+2",
    action: "group2",
  },
  {
    keys: "Any+3",
    action: "group3",
  },
  {
    keys: "Any+4",
    action: "group4",
  },
  {
    keys: "Any+5",
    action: "group5",
  },
  {
    keys: "Any+6",
    action: "group6",
  },
  {
    keys: "Any+7",
    action: "group7",
  },
  {
    keys: "Any+8",
    action: "group8",
  },
  {
    keys: "Any+9",
    action: "group9",
  },
  {
    keys: "[",
    action: "buildfacing inc",
  },
  {
    keys: "Shift+[",
    action: "buildfacing inc",
  },
  {
    keys: "]",
    action: "buildfacing dec",
  },
  {
    keys: "Shift+]",
    action: "buildfacing dec",
  },
  {
    keys: "Any+z",
    action: "buildspacing inc",
  },
  {
    keys: "Any+x",
    action: "buildspacing dec",
  },
  {
    keys: "a",
    action: "attack",
  },
  {
    keys: "Shift+a",
    action: "attack",
  },
  {
    keys: "Alt+a",
    action: "areaattack",
  },
  {
    keys: "Alt+Shift+a",
    action: "areaattack",
  },
  {
    keys: "Alt+b",
    action: "debug",
  },
  {
    keys: "Alt+v",
    action: "debugcolvol",
  },
  {
    keys: "Alt+p",
    action: "debugpath",
  },
  {
    keys: "d",
    action: "manualfire",
  },
  {
    keys: "Shift+d",
    action: "manualfire",
  },
  {
    keys: "Ctrl+d",
    action: "selfd",
  },
  {
    keys: "Ctrl+Shift+d",
    action: "selfd queued",
  },
  {
    keys: "e",
    action: "reclaim",
  },
  {
    keys: "Shift+e",
    action: "reclaim",
  },
  {
    keys: "f",
    action: "fight",
  },
  {
    keys: "Shift+f",
    action: "fight",
  },
  {
    keys: "Alt+f",
    action: "forcestart",
  },
  {
    keys: "g",
    action: "guard",
  },
  {
    keys: "Shift+g",
    action: "guard",
  },
  {
    keys: "k",
    action: "cloak",
  },
  {
    keys: "Shift+k",
    action: "cloak",
  },
  {
    keys: "l",
    action: "loadunits",
  },
  {
    keys: "Shift+l",
    action: "loadunits",
  },
  {
    keys: "m",
    action: "move",
  },
  {
    keys: "Shift+m",
    action: "move",
  },
  {
    keys: "Alt+o",
    action: "singlestep",
  },
  {
    keys: "p",
    action: "patrol",
  },
  {
    keys: "Shift+p",
    action: "patrol",
  },
  {
    keys: "q",
    action: "groupselect",
  },
  {
    keys: "q",
    action: "groupadd",
  },
  {
    keys: "Ctrl+q",
    action: "aiselect",
  },
  {
    keys: "Shift+q",
    action: "groupclear",
  },
  {
    keys: "r",
    action: "repair",
  },
  {
    keys: "Shift+r",
    action: "repair",
  },
  {
    keys: "s",
    action: "stop",
  },
  {
    keys: "Shift+s",
    action: "stop",
  },
  {
    keys: "u",
    action: "unloadunits",
  },
  {
    keys: "Shift+u",
    action: "unloadunits",
  },
  {
    keys: "w",
    action: "wait",
  },
  {
    keys: "Shift+w",
    action: "wait queued",
  },
  {
    keys: "x",
    action: "onoff",
  },
  {
    keys: "Shift+x",
    action: "onoff",
  },
  {
    keys: "Ctrl+t",
    action: "trackmode",
  },
  {
    keys: "Any+t",
    action: "track",
  },
  {
    keys: "Ctrl+f1",
    action: "viewfps",
  },
  {
    keys: "Ctrl+f2",
    action: "viewta",
  },
  {
    keys: "Ctrl+f3",
    action: "viewspring",
  },
  {
    keys: "Ctrl+f4",
    action: "viewrot",
  },
  {
    keys: "Ctrl+f5",
    action: "viewfree",
  },
  {
    keys: "Any+f1",
    action: "ShowElevation",
  },
  {
    keys: "Any+f2",
    action: "ShowPathTraversability",
  },
  {
    keys: "Any+f3",
    action: "LastMsgPos",
  },
  {
    keys: "Any+f4",
    action: "ShowMetalMap",
  },
  {
    keys: "Any+f5",
    action: "HideInterface",
  },
  {
    keys: "Any+f6",
    action: "MuteSound",
  },
  {
    keys: "Any+l",
    action: "togglelos",
  },
  {
    keys: "Ctrl+Shift+f8",
    action: "savegame",
  },
  {
    keys: "Ctrl+Shift+f10",
    action: "createvideo",
  },
  {
    keys: "Any+f11",
    action: "screenshot",
  },
  {
    keys: "Any+f12",
    action: "screenshot",
  },
  {
    keys: "Alt+enter",
    action: "fullscreen",
  },
  {
    keys: "Any+`,Any+`",
    action: "drawlabel",
  },
  {
    keys: "Any+\\\\,Any+\\\\",
    action: "drawlabel",
  },
  {
    keys: "Any+~,Any+~",
    action: "drawlabel",
  },
  {
    keys: "Any+§,Any+§",
    action: "drawlabel",
  },
  {
    keys: "Any+^,Any+^",
    action: "drawlabel",
  },
  {
    keys: "Any+`",
    action: "drawinmap",
  },
  {
    keys: "Any+\\\\",
    action: "drawinmap",
  },
  {
    keys: "Any+~",
    action: "drawinmap",
  },
  {
    keys: "Any+§",
    action: "drawinmap",
  },
  {
    keys: "Any+^",
    action: "drawinmap",
  },
  {
    keys: "Any+up",
    action: "moveforward",
  },
  {
    keys: "Any+down",
    action: "moveback",
  },
  {
    keys: "Any+right",
    action: "moveright",
  },
  {
    keys: "Any+left",
    action: "moveleft",
  },
  {
    keys: "Any+pageup",
    action: "moveup",
  },
  {
    keys: "Any+pagedown",
    action: "movedown",
  },
  {
    keys: "Any+ctrl",
    action: "moveslow",
  },
  {
    keys: "Any+shift",
    action: "movefast",
  },
  {
    keys: "Any+ctrl",
    action: "movetilt",
  },
  {
    keys: "Any+alt",
    action: "movereset",
  },
  {
    keys: "Any+alt",
    action: "moverotate",
  },
  {
    keys: "Ctrl+a",
    action: "select AllMap++_ClearSelection_SelectAll+",
  },
  {
    keys: "Ctrl+b",
    action: "select AllMap+_Builder_Idle+_ClearSelection_SelectOne+",
  },
  {
    keys: "Ctrl+c",
    action: "select AllMap+_ManualFireUnit+_ClearSelection_SelectOne+",
  },
  {
    keys: "Ctrl+r",
    action: "select AllMap+_Radar+_ClearSelection_SelectAll+",
  },
  {
    keys: "Ctrl+v",
    action:
      "select AllMap+_Not_Builder_Not_Commander_InPrevSel_Not_InHotkeyGroup+_SelectAll+",
  },
  {
    keys: "Ctrl+w",
    action: "select AllMap+_Not_Aircraft_Weapons+_ClearSelection_SelectAll+",
  },
  {
    keys: "Ctrl+x",
    action: "select AllMap+_InPrevSel_Not_InHotkeyGroup+_SelectAll+",
  },
  {
    keys: "Ctrl+z",
    action: "select AllMap+_InPrevSel+_ClearSelection_SelectAll+",
  },
];

/** Every key name the engine will parse, so the keyboard can be labelled with them. */
export const ENGINE_KEY_NAMES: string[] = [
  " ",
  "!",
  '"',
  "#",
  "$",
  "%",
  "&",
  "'",
  "(",
  ")",
  "*",
  "+",
  ",",
  "-",
  ".",
  "/",
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  ":",
  ";",
  "<",
  "=",
  ">",
  "?",
  "@",
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
  "[",
  "\\",
  "]",
  "^",
  "_",
  "`",
  "a",
  "alt",
  "b",
  "backquote",
  "backspace",
  "break",
  "c",
  "capslock",
  "caret",
  "clear",
  "compose",
  "ctrl",
  "d",
  "delete",
  "down",
  "e",
  "end",
  "enter",
  "esc",
  "escape",
  "euro",
  "f",
  "f1",
  "f10",
  "f11",
  "f12",
  "f2",
  "f3",
  "f4",
  "f5",
  "f6",
  "f7",
  "f8",
  "f9",
  "g",
  "h",
  "help",
  "home",
  "i",
  "insert",
  "j",
  "k",
  "l",
  "left",
  "m",
  "menu",
  "meta",
  "mode",
  "mouse",
  "n",
  "numlock",
  "numpad*",
  "numpad+",
  "numpad-",
  "numpad.",
  "numpad/",
  "numpad0",
  "numpad1",
  "numpad2",
  "numpad3",
  "numpad4",
  "numpad5",
  "numpad6",
  "numpad7",
  "numpad8",
  "numpad9",
  "numpad=",
  "numpad_enter",
  "o",
  "p",
  "pagedown",
  "pageup",
  "pause",
  "power",
  "print",
  "printscreen",
  "q",
  "r",
  "return",
  "right",
  "s",
  "scrollock",
  "shift",
  "space",
  "super",
  "sysreq",
  "t",
  "tab",
  "tilde",
  "u",
  "undo",
  "up",
  "v",
  "w",
  "x",
  "y",
  "z",
  "{",
  "|",
  "}",
  "~",
  "§",
  "¨",
  "²",
  "´",
  "ß",
  "ä",
  "ç",
  "ö",
  "ù",
  "ü",
];
