// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-lobby-servers:default`.
const COMMANDS: &[&str] = &[
    "ls_store_credential",
    "ls_get_credential",
    "ls_delete_credential",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
