// Commands exposed by this plugin. The tauri-plugin build helper turns each
// into autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-mapconv:default`.
const COMMANDS: &[&str] = &[
    "mc_probe",
    "mc_suggest_sources",
    "mc_compile",
    "mc_decompile",
    "mc_cancel",
    "mc_open_path",
    "mc_settings_load",
    "mc_settings_save",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
