// Commands exposed by this plugin. The tauri-plugin build helper turns each
// into autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-anim:default`.
const COMMANDS: &[&str] = &["anim_cob_disasm", "anim_bos2cob", "anim_reveal"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
