// Commands exposed by this plugin. The tauri-plugin build helper turns each
// into autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-downloads:default`.
const COMMANDS: &[&str] = &[
    "dl_version",
    "dl_repos",
    "dl_versions",
    "dl_download",
    "dl_springfiles_list",
    "dl_springfiles_engines",
    "dl_bar_maps",
    "dl_download_map",
    "dl_download_file",
    "dl_recoil_engines",
    "dl_download_engine_recoil",
    "dl_download_engine_spring",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
