// Commands exposed by this plugin. The tauri-plugin build helper turns each
// into autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-downloads:default`.
const COMMANDS: &[&str] = &["dl_version", "dl_repos", "dl_versions", "dl_download"];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
