// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-runlite:default`.
const COMMANDS: &[&str] = &[
    "runlite_state_load",
    "runlite_state_save",
    "runlite_meta_load",
    "runlite_meta_save",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
