// Commands exposed by this plugin. The tauri-plugin build helper turns each into
// autogenerated `allow-<cmd>` / `deny-<cmd>` permissions (snake_case ->
// kebab-case), which `permissions/default.toml` aggregates into
// `coilbox-multiplayer:default`.
const COMMANDS: &[&str] = &[
    "mp_connect",
    "mp_disconnect",
    "mp_reattach",
    "mp_active_keys",
    "mp_snapshot",
    "mp_send",
    "mp_say",
    "mp_say_private",
    "mp_join_channel",
    "mp_leave_channel",
    "mp_list_channels",
    "mp_join_battle",
    "mp_leave_battle",
    "mp_set_status",
    "mp_set_battle_status",
    "mp_open_battle",
    "mp_add_bot",
    "mp_remove_bot",
    "mp_update_bot",
    "mp_force_team",
    "mp_force_ally",
    "mp_force_color",
    "mp_force_spectator",
    "mp_kick",
    "mp_set_start_rect",
    "mp_set_script_tags",
    "mp_build_battle_config",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
